/**
 * mTLS Agent CA Service
 *
 * Bootstraps a self-signed CA used to sign per-agent client certificates for
 * sidecars connecting to the customer's SILO Cortex. Idempotent — only generates
 * a CA when the configured Secrets Manager entry is empty/placeholder.
 *
 * Customer opt-in: set `MTLS_AGENT_CA_ENABLED=true`.
 *
 * Secret shape (JSON, stored at MTLS_CA_SECRET_NAME):
 *   { certPem: string, keyPem: string, createdAt: string,
 *     commonName: string, validityYears: number }
 */

import {
  GetSecretValueCommand,
  PutSecretValueCommand,
  ResourceNotFoundException,
  CreateSecretCommand,
} from '@aws-sdk/client-secrets-manager';
import forge from 'node-forge';
import { config } from '../config/index.js';
import { createSecretsManagerClient, getAWSRegion } from '../config/aws.js';
import { logger } from './logger.service.js';

export interface CABundle {
  certPem: string;
  keyPem: string;
  createdAt: string;
  commonName: string;
  validityYears: number;
}

let cachedBundle: CABundle | null = null;

export function isMtlsCaEnabled(): boolean {
  return config.MTLS_AGENT_CA_ENABLED === 'true';
}

function secretsClient() {
  // Region override: MTLS_CA_REGION wins over the default chain.
  if (config.MTLS_CA_REGION) {
    const orig = process.env.AWS_REGION;
    process.env.AWS_REGION = config.MTLS_CA_REGION;
    const c = createSecretsManagerClient();
    if (orig !== undefined) process.env.AWS_REGION = orig;
    else delete process.env.AWS_REGION;
    return c;
  }
  return createSecretsManagerClient();
}

function isPopulatedBundle(parsed: unknown): parsed is CABundle {
  return (
    typeof parsed === 'object' &&
    parsed !== null &&
    typeof (parsed as Record<string, unknown>).certPem === 'string' &&
    typeof (parsed as Record<string, unknown>).keyPem === 'string' &&
    ((parsed as Record<string, unknown>).certPem as string).includes('BEGIN CERTIFICATE') &&
    ((parsed as Record<string, unknown>).keyPem as string).includes('PRIVATE KEY')
  );
}

function generateSelfSignedCA(): CABundle {
  const validityYears = parseInt(config.MTLS_CA_VALIDITY_YEARS, 10);
  const commonName = config.MTLS_CA_COMMON_NAME;
  const org = config.MTLS_CA_ORG;

  logger.info('Generating self-signed mTLS agent CA', { commonName, org, validityYears });

  const keys = forge.pki.rsa.generateKeyPair({ bits: 4096, e: 0x10001 });
  const cert = forge.pki.createCertificate();
  cert.publicKey = keys.publicKey;
  cert.serialNumber = '01' + forge.util.bytesToHex(forge.random.getBytesSync(15));
  cert.validity.notBefore = new Date();
  cert.validity.notAfter = new Date();
  cert.validity.notAfter.setFullYear(
    cert.validity.notBefore.getFullYear() + validityYears,
  );

  const attrs = [
    { name: 'commonName', value: commonName },
    { name: 'organizationName', value: org },
  ];
  cert.setSubject(attrs);
  cert.setIssuer(attrs);

  cert.setExtensions([
    { name: 'basicConstraints', cA: true, critical: true, pathLenConstraint: 1 },
    {
      name: 'keyUsage',
      critical: true,
      keyCertSign: true,
      cRLSign: true,
      digitalSignature: true,
    },
    { name: 'subjectKeyIdentifier' },
  ]);

  cert.sign(keys.privateKey, forge.md.sha256.create());

  return {
    certPem: forge.pki.certificateToPem(cert),
    keyPem: forge.pki.privateKeyToPem(keys.privateKey),
    createdAt: new Date().toISOString(),
    commonName,
    validityYears,
  };
}

async function readSecret(secretId: string): Promise<string | null> {
  const client = secretsClient();
  try {
    const out = await client.send(new GetSecretValueCommand({ SecretId: secretId }));
    return out.SecretString ?? null;
  } catch (err) {
    if (err instanceof ResourceNotFoundException) return null;
    throw err;
  }
}

async function writeSecret(secretId: string, json: string): Promise<void> {
  const client = secretsClient();
  try {
    await client.send(new PutSecretValueCommand({ SecretId: secretId, SecretString: json }));
  } catch (err) {
    if (err instanceof ResourceNotFoundException) {
      await client.send(
        new CreateSecretCommand({
          Name: secretId,
          SecretString: json,
          Description: 'mTLS agent CA — autogenerated by license-server (MTLS_AGENT_CA_ENABLED)',
        }),
      );
      return;
    }
    throw err;
  }
}

/**
 * Idempotent. Returns the active CA bundle, bootstrapping (and persisting)
 * one if the configured secret is empty or holds only a placeholder.
 *
 * Throws if MTLS_AGENT_CA_ENABLED is not 'true' — callers should check
 * isMtlsCaEnabled() first.
 */
export async function ensureCA(): Promise<CABundle> {
  if (!isMtlsCaEnabled()) {
    throw new Error('mTLS agent CA is disabled (MTLS_AGENT_CA_ENABLED != true)');
  }
  if (cachedBundle) return cachedBundle;

  const secretId = config.MTLS_CA_SECRET_NAME;
  const region = config.MTLS_CA_REGION ?? getAWSRegion();

  logger.info('Loading mTLS CA from Secrets Manager', { secretId, region });

  const raw = await readSecret(secretId);
  if (raw) {
    try {
      const parsed = JSON.parse(raw);
      if (isPopulatedBundle(parsed)) {
        logger.info('mTLS CA already present — using existing', {
          secretId,
          commonName: parsed.commonName,
          createdAt: parsed.createdAt,
        });
        cachedBundle = parsed;
        return parsed;
      }
      logger.info('mTLS CA secret holds placeholder — bootstrapping', { secretId });
    } catch {
      logger.warn('mTLS CA secret is not valid JSON — bootstrapping fresh', { secretId });
    }
  } else {
    logger.info('mTLS CA secret does not exist — will create', { secretId });
  }

  const bundle = generateSelfSignedCA();
  await writeSecret(secretId, JSON.stringify(bundle));
  logger.info('mTLS CA bootstrapped and stored', {
    secretId,
    commonName: bundle.commonName,
    validityYears: bundle.validityYears,
  });

  cachedBundle = bundle;
  return bundle;
}

/**
 * Returns the cached CA without re-reading from Secrets Manager.
 * Throws if ensureCA() has not been called.
 */
export function getCachedCA(): CABundle {
  if (!cachedBundle) {
    throw new Error('CA not initialized — call ensureCA() at startup');
  }
  return cachedBundle;
}

/** Test-only: clear the in-memory cache. */
export function _resetCAForTests(): void {
  cachedBundle = null;
}
